/**
 * Fleet registry — the live client sites you've shipped.
 *
 * This is a hand-maintained list (add a line when you launch a client). Keeping
 * it manual is deliberate: the gallery should only show sites you've chosen to
 * track, not auto-discover half-built apps. Thumbnails are generated by a
 * screenshot service from the live URL, so they need a real, public `url`.
 */
export interface FleetSite {
  slug: string;
  name: string;
  /** Live production URL. Thumbnails only render once this is public. */
  url: string;
  trade: string;
  /** Template version the site shipped on (for fleet-drift tracking). */
  templateVersion?: string;
  status: "live" | "preview" | "handed-off";
}

export const FLEET: FleetSite[] = [
  {
    slug: "demo-pressure-pros",
    name: "Pressure Pros (demo)",
    url: "https://example.com",
    trade: "pressure-washing",
    templateVersion: "0.1.0",
    status: "preview",
  },
  // Add launched clients here, e.g.:
  // { slug: "mikes-junk", name: "Mike's Junk Removal", url: "https://mikesjunk.com",
  //   trade: "junk-removal", templateVersion: "0.1.0", status: "live" },
];

/**
 * Build a thumbnail URL for a site. Uses Microlink's free screenshot endpoint
 * (no key) — swap for ScreenshotOne/Urlbox + an API key for production volume.
 */
export function thumbnailUrl(siteUrl: string): string {
  const params = new URLSearchParams({
    url: siteUrl,
    screenshot: "true",
    meta: "false",
    embed: "screenshot.url",
    viewport: JSON.stringify({ width: 1280, height: 800 }),
  });
  return `https://api.microlink.io/?${params.toString()}`;
}
